### ISSUE TITLE
Wrong output

### ISSUE THREAD

**Issue by yilinhan** [sipa/minisketch#16]
With the following input:
a:[62997785125752341,16259198011488262487]
b:[13517358214702166750,62997785125752341]
minisketch_create(64, 0, 1);

Output:
1 difference is found, value is -294048887

**Comment by sipa** [comment]
Duplicate of #12.

Trying to decode a sketch with more elements in it than its capacity allows, will in some cases lead to random output.

**Comment by gmaxwell** [comment]
Perhaps the example should be changed to include a 'successful' overfull decode.
