### ISSUE TITLE
Clang "unused function EnableClmul" warning on 32-bit systems

### ISSUE THREAD

**Issue by hebasto** [sipa/minisketch#53]
Compiling Bitcoin Core, the recent master branch (https://github.com/bitcoin/bitcoin/commit/57982f419e36d0023c83af2dd0d683ca3160dc2a):

```
$ clang-12 --version
Ubuntu clang version 12.0.0-3ubuntu1~20.04.4
Target: armv7l-unknown-linux-gnueabihf
Thread model: posix
InstalledDir: /usr/bin
$ make
...
  CXX      minisketch/src/libminisketch_a-minisketch.o
minisketch/src/minisketch.cpp:66:20: warning: unused function 'EnableClmul' [-Wunused-function]
static inline bool EnableClmul()
                   ^
1 warning generated.
...
```

**Comment by ajtowns** [comment]
I get this when building bitcoin's fuzzer.

`EnableClmul` is only invoked when `HAVE_CLMUL` is defined, so moving the `#ifdef HAVE_CLMUL / #endif` to wrap the function would solve this.
