### ISSUE TITLE
warning: shift count >= width of type [-Wshift-count-overflow]

### ISSUE THREAD

**Issue by theuni** [sipa/minisketch#9]
Clang spits out lots of these warnings, I assume they all have the same cause.

Looks like an unsigned char is being shifted 8 bits. From a quick glance, it seems to be unreachable.

> In file included from src/fields/generic_1byte.cpp:11:
In file included from src/fields/generic_common_impl.h:13:
src/fields/../int_utils.h:69:17: warning: shift count >= width of type [-Wshift-count-overflow]
            val >>= 8;
                ^   ~
src/fields/generic_common_impl.h:78:57: note: in instantiation of function template specialization 'BitWriter::Write<2, unsigned char>' requested here
    void Serialize(BitWriter& out) const { out.template Write<BITS, I>(m_val); }
                                                        ^
src/fields/../sketch_impl.h:378:17: note: in instantiation of member function '(anonymous namespace)::Field<unsigned char, 2, 3, RecLinTrans<unsigned char, 2>, RecLinTrans<unsigned char, 2>, &(anonymous namespace)::SQR_TABLE_2, &(anonymous namespace)::QRT_TABLE_2>::Serialize' requested here
            val.Serialize(writer);
                ^
src/fields/../sketch_impl.h:359:5: note: in instantiation of member function 'SketchImpl<(anonymous namespace)::Field<unsigned char, 2, 3, RecLinTrans<unsigned char, 2>, RecLinTrans<unsigned char, 2>, &(anonymous namespace)::SQR_TABLE_2, &(anonymous namespace)::QRT_TABLE_2> >::Serialize' requested here
    SketchImpl(int implementation) : Sketch(implementation, F::BITS) {
    ^
src/fields/generic_1byte.cpp:73:24: note: in instantiation of member function 'SketchImpl<(anonymous namespace)::Field<unsigned char, 2, 3, RecLinTrans<unsigned char, 2>, RecLinTrans<unsigned char, 2>, &(anonymous namespace)::SQR_TABLE_2, &(anonymous namespace)::QRT_TABLE_2> >::SketchImpl' requested here
    case 2: return new SketchImpl<Field2>(implementation);

**Comment by gmaxwell** [comment]
Does the following silence it for you?

```
diff --git a/src/int_utils.h b/src/int_utils.h
index cbf983f..95d7675 100644
--- a/src/int_utils.h
+++ b/src/int_utils.h
@@ -64,10 +64,12 @@ public:
             offset = 0;
             state = 0;
         }
-        while (bits >= 8) {
-            *(out++) = val & 255;
-            val >>= 8;
-            bits -= 8;
+        if (sizeof(val) > 1){
+            while (bits >= 8) {
+                *(out++) = val & 255;
+                val >>= 8;
+                bits -= 8;
+            }
         }
         state |= ((val & ((I(1) << bits) - 1)) << offset);
         offset += bits;
```
?

**Comment by theuni** [comment]
@gmaxwell yup, works :)

In the same vein, this also works:
```diff
diff --git a/src/int_utils.h b/src/int_utils.h
index cbf983f..9c52dbd 100644
--- a/src/int_utils.h
+++ b/src/int_utils.h
@@ -64,7 +64,7 @@ public:
             offset = 0;
             state = 0;
         }
-        while (bits >= 8) {
+        while (BITS > 8 && bits >= 8) {
             *(out++) = val & 255;
             val >>= 8;
             bits -= 8;
```

**Comment by gmaxwell** [comment]
@theuni  interesting, I reproed your issue with clang 5.0.2 but the warning was not silenced by putting a BITS > 8 test as an IF around the while loop.

**Comment by gmaxwell** [comment]
The current code is warning free w/ Clang 9.0.0.

**Comment by sipa** [comment]
Cool.
